/*
 * Robot service 3.0
 * API сервис управления роботом - пылесосом
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Cleaning;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for LeaningApi
 */
@Ignore
public class LeaningApiTest {

    private final LeaningApi api = new LeaningApi();

    /**
     * Добавить уборку
     *
     * Добавить уборку по ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCleaningTest() throws Exception {
        Cleaning body = null;
        Cleaning response = api.addCleaning(body);

        // TODO: test validations
    }
    /**
     * Удаляет уборку
     *
     * Удаляет уборку
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteleaningTest() throws Exception {
        Long leaningId = null;
        String leaningId = null;
        api.deleteleaning(leaningId, leaningId);

        // TODO: test validations
    }
    /**
     * Найти уборку по ID
     *
     * Вернуть уборку по ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getleaningByIdTest() throws Exception {
        Long leaningId = null;
        Cleaning response = api.getleaningById(leaningId);

        // TODO: test validations
    }
    /**
     * Обновить уборку
     *
     * Обновить убоку
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateleaningTest() throws Exception {
        Cleaning body = null;
        Cleaning response = api.updateleaning(body);

        // TODO: test validations
    }
}
